CREATE TABLE order_side(
    id int PRIMARY KEY NOT NULL,
    side_value text NOT NULL
);

CREATE TABLE order_type(
    id int PRIMARY KEY NOT NULL,
    type_value text NOT NULL
);

CREATE TABLE order_status(
  id int PRIMARY KEY NOT NULL,
  status_value text NOT NULL
);

CREATE TABLE exchange(
    id int PRIMARY KEY NOT NULL,
    exchange_name text NOT null,
    display_name text NOT null
);

CREATE TABLE trade_strategy(
    id int PRIMARY KEY NOT NULL,
    strategy_name text NOT null
);


CREATE TABLE account(
    id integer primary key generated always as identity,
    balance NUMERIC(10,4) NOT NULL,
    risk_percentage NUMERIC(5,2) NOT NULL,
    currency text,
    derivate text NOT NULL,
	exchange_id int NOT NULL REFERENCES exchange(id)
);

CREATE TABLE trade(
  id integer primary key generated always as identity,
  risk_reward NUMERIC(5,2),
  late_entry int NOT NULL,
  candle_close_entry boolean,
  attempt int NOT NULL,
  percentage_entry boolean,
  symbol text,
  created_date timestamp,
  account_id int NOT NULL REFERENCES account(id),
  trade_strategy_id int NOT NULL REFERENCES trade_strategy(id)
);

CREATE TABLE trade_order(
	id int primary key GENERATED BY DEFAULT AS IDENTITY,
	quantity NUMERIC(10,4) NOT NULL,
	activation_price NUMERIC(10,4),
	filled_price NUMERIC(10,4),
	fee NUMERIC(10,4),
	realized_profit  NUMERIC(10,4),
	created_date timestamp,
	closed_date timestamp,
	exchange_transaction text,
	parent_trade int REFERENCES trade_order(id),
	category varchar (2),
	side_id int NOT NULL REFERENCES order_side(id),
	type_id int NOT NULL REFERENCES order_type(id),
	status_id int NOT NULL REFERENCES order_status(id),
    trade_id int NOT NULL REFERENCES trade(id)
);

INSERT INTO trade_strategy (id,strategy_name) VALUES (1,'Trend Following');
INSERT INTO exchange  (id, exchange_name , display_name) VALUES (1,'Binance', 'Binance');
INSERT INTO account (balance, risk_percentage, currency, derivate, exchange_id) 
VALUES (10000.00, 5.50, 'USD', 'Futures', 1);

INSERT INTO account (balance, risk_percentage, currency, derivate, exchange_id) 
VALUES (5000.00, 3.75, 'EUR', 'Options', 2);

INSERT INTO account (balance, risk_percentage, currency, derivate, exchange_id) 
VALUES (7500.00, 4.25, 'GBP', 'Futures', 1);

-- assuming we have the following foreign key values: 
-- account_id = 1, strategy_id = 3
INSERT INTO trade (risk_reward, late_entry, candle_close_entry, attempt, percentage_entry, symbol, created_date, account_id, trade_strategy_id) 
VALUES (2.10, 5, true, 2, false, 'AAPL', '2022-10-03', 1, 1);

-- assuming we have the following foreign key values: 
-- account_id = 2, strategy_id = 1
INSERT INTO trade (risk_reward, late_entry, candle_close_entry, attempt, percentage_entry, symbol, created_date, account_id, strategy_id) 
VALUES (3.20, 2, false, 3, true, 'GOOG', '2022-11-15', 2, 1);

-- assuming we have the following foreign key values: 
-- account_id = 3, strategy_id = 2
INSERT INTO trade (risk_reward, late_entry, candle_close_entry, attempt, percentage_entry, symbol, created_date, account_id, strategy_id) 
VALUES (1.50, 7, true, 1, true, 'FB', '2022-12-01', 3, 2);


ALTER TABLE account ADD unique (derivate, exchange_id);
ALTER TABLE account ADD CONSTRAINT fk_exchange_id FOREIGN KEY (exchange_id) REFERENCES exchange(id);
ALTER TABLE trade ADD CONSTRAINT fk_account_id FOREIGN KEY (account_id) REFERENCES account(id);
ALTER TABLE trade_order ADD CONSTRAINT fk_trade_id FOREIGN KEY (trade_id) REFERENCES trade(id);
ALTER TABLE trade_order ADD CONSTRAINT fk_side_id FOREIGN KEY (side_id) REFERENCES order_side(id);
ALTER TABLE trade_order ADD CONSTRAINT fk_type_id FOREIGN KEY (type_id) REFERENCES order_type(id);
ALTER TABLE trade_order ADD CONSTRAINT fk_status_id FOREIGN KEY (status_id) REFERENCES order_status(id);


drop table trade_order;
drop table order_type;
drop table order_status;
drop table trade;
drop table trade_strategy;
drop table account;
drop table exchange;
drop table order_side;






SELECT *
FROM information_schema.columns
WHERE table_value = 'account';

select concat('alter table public.test1 drop constraint ', constraint_value) as my_query
from information_schema.table_constraints
where table_schema = 'public'
      and table_value = 'account'
      and constraint_type = 'PRIMARY KEY';


INSERT INTO order_side (id, value) VALUES (0, 'Buy');
INSERT INTO order_side (id,value) VALUES (1, 'Sell');

INSERT INTO order_type (id,value) VALUES (0, 'Limit');
INSERT INTO order_type (id,value) VALUES (1, 'Market');
INSERT INTO order_type (id,value) VALUES (2, 'Stop');
INSERT INTO order_type (id,value) VALUES (3, 'StopMarket');
INSERT INTO order_type (id,value) VALUES (4, 'TakeProfit');
INSERT INTO order_type (id,value) VALUES (5, 'TakeProfitMarket');
INSERT INTO order_type (id,value) VALUES (6, 'TrailingStopMarket');


INSERT INTO trade_mode (id,value) VALUES (0, 'Normal');
INSERT INTO trade_mode (id,value, risk_reward) VALUES (1, 'NormalSecure', 3);
INSERT INTO trade_mode (id,value, risk_reward) VALUES (2, 'Grid', 2);
INSERT INTO trade_mode (id,value, risk_reward) VALUES (3, 'GridSecure', 4);

INSERT INTO order_status (id,value) VALUES (0, 'New');
INSERT INTO order_status (id,value) VALUES (1, 'PartiallyFilled');
INSERT INTO order_status (id,value) VALUES (2, 'Filled');
INSERT INTO order_status (id,value) VALUES (3, 'Canceled');
INSERT INTO order_status (id,value) VALUES (4, 'PendingCancel');
INSERT INTO order_status (id,value) VALUES (5, 'Rejected');
INSERT INTO order_status (id,value) VALUES (6, 'Expired');

INSERT INTO account
(derivates, risk,  balance, currency)
VALUES('FUTURES', 1, 200, 'BUSD');

INSERT INTO account
(derivates, risk,  balance, currency)
VALUES('FUTURES', 1, 200, 'USDT');

INSERT INTO account
(derivates, risk,  balance, currency)
VALUES('COIN', 1, 0.05,  'BTC');

INSERT INTO account
(derivates, risk,  balance, currency)
VALUES('COIN', 1, 0.10,  'ETH');

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('BTCBUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('ETHBUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('BNBBUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('ADABUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('SOLBUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('XRPBUSD', now(), 1);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('ADAUSDT', now(), 2);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('BTCBUSDT', now(), 2);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('ETHUSDT', now(), 2);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('BNBUSDT', now(), 2);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('SOLUSDT', now(), 2);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('BTCUSD_PERP', now(), 3);

INSERT INTO trade_system
(symbol, created_date , account_id)
VALUES('ETHUSD_PERP', now(), 4);



